### ISSUE TITLE
Feature Request: Unscaled Timers

### ISSUE THREAD

**Issue by TheXRMonk** [elraccoone/unity-timers#2]
The title says it all :)

**Comment by jeffreylanters** [comment]
Now we're talking about it, shouldn't timers always be unscaled. What do you think about it?

**Comment by jeffreylanters** [comment]
I've changed the behaviour to Unscaled time in version [1.2.0](https://github.com/elraccoone/unity-timers/releases/tag/1.2.0). Thanks for opening this issue.

**Comment by TheXRMonk** [comment]
Yea they should be unscaled by default - still nice with an option for scaled in some edge cases.
Thanks for the quick update!
