### ISSUE TITLE
Sub-second timers don't work due to not casting int to float

### ISSUE THREAD

**Issue by tsortwehttam** [elraccoone/unity-timers#3]
https://github.com/jeffreylanters/unity-timers/blob/master/Runtime/TimerTicker.cs#L8

These division operations will result in `int` values. The `milisecond` var needs to be cast to `(float)`.

For example, if I put `1500` it gets rounded to `1` instead of `1.5`.

**Comment by jeffreylanters** [comment]
Well spotted! I've published a hot fix 1.2.2.
